[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "code_vibing"
version = "0.0.1"
dependencies = [
    "python-vlc",
    'importlib-metadata; python_version>="3.11"',
]
